networks:
  app-net:
    driver: bridge

volumes:
  sqlserver-data:

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Password123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Password123 -Q 'SELECT 1' -No"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-net

  backend:
    build:
      context: ./Lunchmate-server
      dockerfile: Lunchmate.API/Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=LunchmateDb;User=sa;Password=YourStrong@Password123;TrustServerCertificate=True"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - app-net

  frontend:
    build:
      context: ./Lunchmate-client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-net